// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/appuser-manager/pkg/db/ent/appcontrol"
	"github.com/google/uuid"
)

// AppControl is the model entity for the AppControl schema.
type AppControl struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// SignupMethods holds the value of the "signup_methods" field.
	SignupMethods []string `json:"signup_methods,omitempty"`
	// ExternSigninMethods holds the value of the "extern_signin_methods" field.
	ExternSigninMethods []string `json:"extern_signin_methods,omitempty"`
	// RecaptchaMethod holds the value of the "recaptcha_method" field.
	RecaptchaMethod string `json:"recaptcha_method,omitempty"`
	// KycEnable holds the value of the "kyc_enable" field.
	KycEnable bool `json:"kyc_enable,omitempty"`
	// SigninVerifyEnable holds the value of the "signin_verify_enable" field.
	SigninVerifyEnable bool `json:"signin_verify_enable,omitempty"`
	// InvitationCodeMust holds the value of the "invitation_code_must" field.
	InvitationCodeMust bool `json:"invitation_code_must,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppControl) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case appcontrol.FieldSignupMethods, appcontrol.FieldExternSigninMethods:
			values[i] = new([]byte)
		case appcontrol.FieldKycEnable, appcontrol.FieldSigninVerifyEnable, appcontrol.FieldInvitationCodeMust:
			values[i] = new(sql.NullBool)
		case appcontrol.FieldCreatedAt, appcontrol.FieldUpdatedAt, appcontrol.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case appcontrol.FieldRecaptchaMethod:
			values[i] = new(sql.NullString)
		case appcontrol.FieldID, appcontrol.FieldAppID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppControl", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppControl fields.
func (ac *AppControl) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appcontrol.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ac.ID = *value
			}
		case appcontrol.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ac.CreatedAt = uint32(value.Int64)
			}
		case appcontrol.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ac.UpdatedAt = uint32(value.Int64)
			}
		case appcontrol.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ac.DeletedAt = uint32(value.Int64)
			}
		case appcontrol.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				ac.AppID = *value
			}
		case appcontrol.FieldSignupMethods:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field signup_methods", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ac.SignupMethods); err != nil {
					return fmt.Errorf("unmarshal field signup_methods: %w", err)
				}
			}
		case appcontrol.FieldExternSigninMethods:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extern_signin_methods", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ac.ExternSigninMethods); err != nil {
					return fmt.Errorf("unmarshal field extern_signin_methods: %w", err)
				}
			}
		case appcontrol.FieldRecaptchaMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recaptcha_method", values[i])
			} else if value.Valid {
				ac.RecaptchaMethod = value.String
			}
		case appcontrol.FieldKycEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field kyc_enable", values[i])
			} else if value.Valid {
				ac.KycEnable = value.Bool
			}
		case appcontrol.FieldSigninVerifyEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field signin_verify_enable", values[i])
			} else if value.Valid {
				ac.SigninVerifyEnable = value.Bool
			}
		case appcontrol.FieldInvitationCodeMust:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field invitation_code_must", values[i])
			} else if value.Valid {
				ac.InvitationCodeMust = value.Bool
			}
		}
	}
	return nil
}

// Update returns a builder for updating this AppControl.
// Note that you need to call AppControl.Unwrap() before calling this method if this AppControl
// was returned from a transaction, and the transaction was committed or rolled back.
func (ac *AppControl) Update() *AppControlUpdateOne {
	return (&AppControlClient{config: ac.config}).UpdateOne(ac)
}

// Unwrap unwraps the AppControl entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ac *AppControl) Unwrap() *AppControl {
	tx, ok := ac.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppControl is not a transactional entity")
	}
	ac.config.driver = tx.drv
	return ac
}

// String implements the fmt.Stringer.
func (ac *AppControl) String() string {
	var builder strings.Builder
	builder.WriteString("AppControl(")
	builder.WriteString(fmt.Sprintf("id=%v", ac.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.CreatedAt))
	builder.WriteString(", updated_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.UpdatedAt))
	builder.WriteString(", deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.DeletedAt))
	builder.WriteString(", app_id=")
	builder.WriteString(fmt.Sprintf("%v", ac.AppID))
	builder.WriteString(", signup_methods=")
	builder.WriteString(fmt.Sprintf("%v", ac.SignupMethods))
	builder.WriteString(", extern_signin_methods=")
	builder.WriteString(fmt.Sprintf("%v", ac.ExternSigninMethods))
	builder.WriteString(", recaptcha_method=")
	builder.WriteString(ac.RecaptchaMethod)
	builder.WriteString(", kyc_enable=")
	builder.WriteString(fmt.Sprintf("%v", ac.KycEnable))
	builder.WriteString(", signin_verify_enable=")
	builder.WriteString(fmt.Sprintf("%v", ac.SigninVerifyEnable))
	builder.WriteString(", invitation_code_must=")
	builder.WriteString(fmt.Sprintf("%v", ac.InvitationCodeMust))
	builder.WriteByte(')')
	return builder.String()
}

// AppControls is a parsable slice of AppControl.
type AppControls []*AppControl

func (ac AppControls) config(cfg config) {
	for _i := range ac {
		ac[_i].config = cfg
	}
}
