// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/appuser-manager/pkg/db/ent/approleuser"
	"github.com/NpoolPlatform/appuser-manager/pkg/db/ent/predicate"
)

// AppRoleUserDelete is the builder for deleting a AppRoleUser entity.
type AppRoleUserDelete struct {
	config
	hooks    []Hook
	mutation *AppRoleUserMutation
}

// Where appends a list predicates to the AppRoleUserDelete builder.
func (arud *AppRoleUserDelete) Where(ps ...predicate.AppRoleUser) *AppRoleUserDelete {
	arud.mutation.Where(ps...)
	return arud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (arud *AppRoleUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(arud.hooks) == 0 {
		affected, err = arud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppRoleUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			arud.mutation = mutation
			affected, err = arud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(arud.hooks) - 1; i >= 0; i-- {
			if arud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = arud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, arud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (arud *AppRoleUserDelete) ExecX(ctx context.Context) int {
	n, err := arud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (arud *AppRoleUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: approleuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: approleuser.FieldID,
			},
		},
	}
	if ps := arud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, arud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// AppRoleUserDeleteOne is the builder for deleting a single AppRoleUser entity.
type AppRoleUserDeleteOne struct {
	arud *AppRoleUserDelete
}

// Exec executes the deletion query.
func (arudo *AppRoleUserDeleteOne) Exec(ctx context.Context) error {
	n, err := arudo.arud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{approleuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (arudo *AppRoleUserDeleteOne) ExecX(ctx context.Context) {
	arudo.arud.ExecX(ctx)
}
