// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/appuser-manager/pkg/db/ent/banappuser"
	"github.com/NpoolPlatform/appuser-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// BanAppUserUpdate is the builder for updating BanAppUser entities.
type BanAppUserUpdate struct {
	config
	hooks    []Hook
	mutation *BanAppUserMutation
}

// Where appends a list predicates to the BanAppUserUpdate builder.
func (bauu *BanAppUserUpdate) Where(ps ...predicate.BanAppUser) *BanAppUserUpdate {
	bauu.mutation.Where(ps...)
	return bauu
}

// SetAppID sets the "app_id" field.
func (bauu *BanAppUserUpdate) SetAppID(u uuid.UUID) *BanAppUserUpdate {
	bauu.mutation.SetAppID(u)
	return bauu
}

// SetUserID sets the "user_id" field.
func (bauu *BanAppUserUpdate) SetUserID(u uuid.UUID) *BanAppUserUpdate {
	bauu.mutation.SetUserID(u)
	return bauu
}

// SetCreateAt sets the "create_at" field.
func (bauu *BanAppUserUpdate) SetCreateAt(u uint32) *BanAppUserUpdate {
	bauu.mutation.ResetCreateAt()
	bauu.mutation.SetCreateAt(u)
	return bauu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (bauu *BanAppUserUpdate) SetNillableCreateAt(u *uint32) *BanAppUserUpdate {
	if u != nil {
		bauu.SetCreateAt(*u)
	}
	return bauu
}

// AddCreateAt adds u to the "create_at" field.
func (bauu *BanAppUserUpdate) AddCreateAt(u int32) *BanAppUserUpdate {
	bauu.mutation.AddCreateAt(u)
	return bauu
}

// SetUpdateAt sets the "update_at" field.
func (bauu *BanAppUserUpdate) SetUpdateAt(u uint32) *BanAppUserUpdate {
	bauu.mutation.ResetUpdateAt()
	bauu.mutation.SetUpdateAt(u)
	return bauu
}

// AddUpdateAt adds u to the "update_at" field.
func (bauu *BanAppUserUpdate) AddUpdateAt(u int32) *BanAppUserUpdate {
	bauu.mutation.AddUpdateAt(u)
	return bauu
}

// SetDeleteAt sets the "delete_at" field.
func (bauu *BanAppUserUpdate) SetDeleteAt(u uint32) *BanAppUserUpdate {
	bauu.mutation.ResetDeleteAt()
	bauu.mutation.SetDeleteAt(u)
	return bauu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (bauu *BanAppUserUpdate) SetNillableDeleteAt(u *uint32) *BanAppUserUpdate {
	if u != nil {
		bauu.SetDeleteAt(*u)
	}
	return bauu
}

// AddDeleteAt adds u to the "delete_at" field.
func (bauu *BanAppUserUpdate) AddDeleteAt(u int32) *BanAppUserUpdate {
	bauu.mutation.AddDeleteAt(u)
	return bauu
}

// Mutation returns the BanAppUserMutation object of the builder.
func (bauu *BanAppUserUpdate) Mutation() *BanAppUserMutation {
	return bauu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bauu *BanAppUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	bauu.defaults()
	if len(bauu.hooks) == 0 {
		affected, err = bauu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BanAppUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bauu.mutation = mutation
			affected, err = bauu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bauu.hooks) - 1; i >= 0; i-- {
			if bauu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bauu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bauu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bauu *BanAppUserUpdate) SaveX(ctx context.Context) int {
	affected, err := bauu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bauu *BanAppUserUpdate) Exec(ctx context.Context) error {
	_, err := bauu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bauu *BanAppUserUpdate) ExecX(ctx context.Context) {
	if err := bauu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bauu *BanAppUserUpdate) defaults() {
	if _, ok := bauu.mutation.UpdateAt(); !ok {
		v := banappuser.UpdateDefaultUpdateAt()
		bauu.mutation.SetUpdateAt(v)
	}
}

func (bauu *BanAppUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   banappuser.Table,
			Columns: banappuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: banappuser.FieldID,
			},
		},
	}
	if ps := bauu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bauu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: banappuser.FieldAppID,
		})
	}
	if value, ok := bauu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: banappuser.FieldUserID,
		})
	}
	if value, ok := bauu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldCreateAt,
		})
	}
	if value, ok := bauu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldCreateAt,
		})
	}
	if value, ok := bauu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldUpdateAt,
		})
	}
	if value, ok := bauu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldUpdateAt,
		})
	}
	if value, ok := bauu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldDeleteAt,
		})
	}
	if value, ok := bauu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bauu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{banappuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// BanAppUserUpdateOne is the builder for updating a single BanAppUser entity.
type BanAppUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BanAppUserMutation
}

// SetAppID sets the "app_id" field.
func (bauuo *BanAppUserUpdateOne) SetAppID(u uuid.UUID) *BanAppUserUpdateOne {
	bauuo.mutation.SetAppID(u)
	return bauuo
}

// SetUserID sets the "user_id" field.
func (bauuo *BanAppUserUpdateOne) SetUserID(u uuid.UUID) *BanAppUserUpdateOne {
	bauuo.mutation.SetUserID(u)
	return bauuo
}

// SetCreateAt sets the "create_at" field.
func (bauuo *BanAppUserUpdateOne) SetCreateAt(u uint32) *BanAppUserUpdateOne {
	bauuo.mutation.ResetCreateAt()
	bauuo.mutation.SetCreateAt(u)
	return bauuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (bauuo *BanAppUserUpdateOne) SetNillableCreateAt(u *uint32) *BanAppUserUpdateOne {
	if u != nil {
		bauuo.SetCreateAt(*u)
	}
	return bauuo
}

// AddCreateAt adds u to the "create_at" field.
func (bauuo *BanAppUserUpdateOne) AddCreateAt(u int32) *BanAppUserUpdateOne {
	bauuo.mutation.AddCreateAt(u)
	return bauuo
}

// SetUpdateAt sets the "update_at" field.
func (bauuo *BanAppUserUpdateOne) SetUpdateAt(u uint32) *BanAppUserUpdateOne {
	bauuo.mutation.ResetUpdateAt()
	bauuo.mutation.SetUpdateAt(u)
	return bauuo
}

// AddUpdateAt adds u to the "update_at" field.
func (bauuo *BanAppUserUpdateOne) AddUpdateAt(u int32) *BanAppUserUpdateOne {
	bauuo.mutation.AddUpdateAt(u)
	return bauuo
}

// SetDeleteAt sets the "delete_at" field.
func (bauuo *BanAppUserUpdateOne) SetDeleteAt(u uint32) *BanAppUserUpdateOne {
	bauuo.mutation.ResetDeleteAt()
	bauuo.mutation.SetDeleteAt(u)
	return bauuo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (bauuo *BanAppUserUpdateOne) SetNillableDeleteAt(u *uint32) *BanAppUserUpdateOne {
	if u != nil {
		bauuo.SetDeleteAt(*u)
	}
	return bauuo
}

// AddDeleteAt adds u to the "delete_at" field.
func (bauuo *BanAppUserUpdateOne) AddDeleteAt(u int32) *BanAppUserUpdateOne {
	bauuo.mutation.AddDeleteAt(u)
	return bauuo
}

// Mutation returns the BanAppUserMutation object of the builder.
func (bauuo *BanAppUserUpdateOne) Mutation() *BanAppUserMutation {
	return bauuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bauuo *BanAppUserUpdateOne) Select(field string, fields ...string) *BanAppUserUpdateOne {
	bauuo.fields = append([]string{field}, fields...)
	return bauuo
}

// Save executes the query and returns the updated BanAppUser entity.
func (bauuo *BanAppUserUpdateOne) Save(ctx context.Context) (*BanAppUser, error) {
	var (
		err  error
		node *BanAppUser
	)
	bauuo.defaults()
	if len(bauuo.hooks) == 0 {
		node, err = bauuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BanAppUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bauuo.mutation = mutation
			node, err = bauuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bauuo.hooks) - 1; i >= 0; i-- {
			if bauuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bauuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bauuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (bauuo *BanAppUserUpdateOne) SaveX(ctx context.Context) *BanAppUser {
	node, err := bauuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bauuo *BanAppUserUpdateOne) Exec(ctx context.Context) error {
	_, err := bauuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bauuo *BanAppUserUpdateOne) ExecX(ctx context.Context) {
	if err := bauuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bauuo *BanAppUserUpdateOne) defaults() {
	if _, ok := bauuo.mutation.UpdateAt(); !ok {
		v := banappuser.UpdateDefaultUpdateAt()
		bauuo.mutation.SetUpdateAt(v)
	}
}

func (bauuo *BanAppUserUpdateOne) sqlSave(ctx context.Context) (_node *BanAppUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   banappuser.Table,
			Columns: banappuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: banappuser.FieldID,
			},
		},
	}
	id, ok := bauuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BanAppUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bauuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, banappuser.FieldID)
		for _, f := range fields {
			if !banappuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != banappuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bauuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bauuo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: banappuser.FieldAppID,
		})
	}
	if value, ok := bauuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: banappuser.FieldUserID,
		})
	}
	if value, ok := bauuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldCreateAt,
		})
	}
	if value, ok := bauuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldCreateAt,
		})
	}
	if value, ok := bauuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldUpdateAt,
		})
	}
	if value, ok := bauuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldUpdateAt,
		})
	}
	if value, ok := bauuo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldDeleteAt,
		})
	}
	if value, ok := bauuo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: banappuser.FieldDeleteAt,
		})
	}
	_node = &BanAppUser{config: bauuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bauuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{banappuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
