// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// AppControl is the predicate function for appcontrol builders.
type AppControl func(*sql.Selector)

// AppRole is the predicate function for approle builders.
type AppRole func(*sql.Selector)

// AppRoleUser is the predicate function for approleuser builders.
type AppRoleUser func(*sql.Selector)

// AppUser is the predicate function for appuser builders.
type AppUser func(*sql.Selector)

// AppUserControl is the predicate function for appusercontrol builders.
type AppUserControl func(*sql.Selector)

// AppUserExtra is the predicate function for appuserextra builders.
type AppUserExtra func(*sql.Selector)

// AppUserSecret is the predicate function for appusersecret builders.
type AppUserSecret func(*sql.Selector)

// AppUserThirdParty is the predicate function for appuserthirdparty builders.
type AppUserThirdParty func(*sql.Selector)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// AuthHistory is the predicate function for authhistory builders.
type AuthHistory func(*sql.Selector)

// BanApp is the predicate function for banapp builders.
type BanApp func(*sql.Selector)

// BanAppUser is the predicate function for banappuser builders.
type BanAppUser func(*sql.Selector)

// Kyc is the predicate function for kyc builders.
type Kyc func(*sql.Selector)

// LoginHistory is the predicate function for loginhistory builders.
type LoginHistory func(*sql.Selector)
